on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v3
      with:
        ref: dev

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        REPO_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker build -t ghcr.io/${REPO_LOWER}/chavarry-deldobackend:latest .

    - name: Push Docker image to GHCR
      if: github.ref == 'refs/heads/main'
      run: |
        REPO_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker push ghcr.io/${REPO_LOWER}/chavarry-deldobackend:latest
