name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Get Dockerfile from dev branch
      run: |
        git fetch origin dev
        git checkout origin/dev -- Dockerfile

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        REPO_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker build -t ghcr.io/${REPO_LOWER}/chavarry-deldobackend:latest .

    - name: Run tests (placeholder)
      run: echo "No tests yet" && exit 0

    - name: Push Docker image to GHCR
      if: github.ref == 'refs/heads/main'
      run: |
        REPO_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker push ghcr.io/${REPO_LOWER}/chavarry-deldobackend:latest
